var artifactsList = {
    "efw21": "A Little Queen's Huge Crown",
    "ef504": "A Symbol of Unity",
    "efm01": "Abyssal Crown",
    "efr17": "Air-to-Surface Missile: MISHA",
    "efa12": "Alabastron",
    "efw13": "Alencinox's Wrath",
    "efa07": "Alexa's Basket",
    "efk14": "Ancient Dragon's Legacy",
    "efw23": "Anti-Magic Mask",
    "efw22": "Azure Comet",
    "ef507": "Bastion of Hope",
    "efk09": "Bastion of Perlutia",
    "efm16": "Black Hand of the Goddess",
    "efr01": "Bloodstone",
    "efm14": "Bloody Rose",
    "efw07": "Border Coin",
    "efh06": "Celestine",
    "efw18": "Champion's Trophy",
    "efm07": "Chatty",
    "efw17": "Circus Fantasia",
    "efw16": "Cradle of Life",
    "efw09": "Creation &amp; Destruction",
    "efm18": "Crimson Moon of Nightmares",
    "efk13": "Crown of Glory",
    "ef503": "Cruel Mischief",
    "efm13": "Dignus Orb",
    "efh12": "Doctor's Bag",
    "efa16": "Double-Edged Decrescent",
    "efw11": "Draco Plate",
    "efw02": "Durandal",
    "efr12": "Dux Noctis",
    "efk02": "Elbris Ritual Sword",
    "efm02": "Etica's Scepter",
    "efh17": "EXIF Detective (E.d.) Gadget",
    "efm19": "Fairy Tale for a Nightmare",
    "efh15": "Flawless Garments",
    "efm28": "Frame of Light",
    "efw28": "Fullmetal's Automail",
    "efr19": "Glo-Wings 21",
    "efa19": "Goblet of Oath",
    "efh14": "Guardian Ice Crystals",
    "ef506": "Guide to a Decision",
    "efr13": "Guiding Light",
    "efk01": "Holy Sacrifice",
    "efh07": "Idol's Cheer",
    "efm26": "Ignition Cloth Gloves",
    "efw26": "Indestructible Gaiters",
    "efr08": "Iron Fan",
    "efw25": "Jack-O's Symbol",
    "efw08": "Junkyard Dog",
    "efk07": "Justice for All",
    "efm20": "Knowledge Seed",
    "efm17": "Last Teatime",
    "efa13": "Manica of Control",
    "efk18": "Mature Sunglasses",
    "efw14": "Merciless Glutton",
    "efr14": "Ms. Confille",
    "efm10": "Necro &amp; Undine",
    "efk06": "Noble Oath",
    "efr06": "Otherworldly Machinery",
    "ef508": "P.O.S",
    "ef501": "Proof of Valor",
    "efw24": "Pure White Trust",
    "efr10": "Reingar's Special Drink",
    "efa01": "Rhianna &amp; Luciella",
    "efk12": "Rise of a Monarch",
    "efk19": "Rocket Punch Gauntlet",
    "efh01": "Rod of Amaryllis",
    "efh16": "Sacred Tree Branch",
    "efw20": "Samsara Prayer Beads",
    "efm25": "Scroll of Shadows",
    "efr22": "Seal of Capture",
    "efa14": "Secret Art - Storm Sword",
    "efm22": "Severed Horn Wand",
    "efr20": "Sharpshooter's Handgun",
    "efa15": "Shepherd of the Hollow",
    "efh02": "Shimadra Staff",
    "efw01": "Sigurd Scythe",
    "efw19": "Snow Crystal",
    "efr02": "Song of Stars",
    "efr21": "Spatiotemporal Fan",
    "efk15": "Spear of a New Dawn",
    "efw27": "Spear of Purification",
    "efr23": "Sphere of Inferno",
    "efk17": "Sphere of Sadism",
    "efm11": "Spirit's Breath",
    "efr18": "Star of the Deep Sea",
    "efh09": "Stella Harpa",
    "efw29": "Sword of Autumn Eclipse",
    "efa20": "Sword of Cycling Seasons",
    "efk08": "Sword of Ezera",
    "efr09": "Sword of Judgment",
    "efa17": "Sword of Summer Twilight",
    "efa18": "Sword of Winter Shadow",
    "efa21": "The Armament",
    "efm06": "Time Matter",
    "efa09": "Torn Sleeve",
    "efh11": "Touch of Rekos",
    "efm21": "Twilight Calamity",
    "efw06": "Uberius's Tooth",
    "efh10": "Unfading Memories",
    "efr16": "Unseen Observer",
    "efm24": "Upgraded Dragon Knuckles",
    "ef502": "Victorious Flag",
    "efa08": "Violet Talisman",
    "efr15": "Wall of Order",
    "ef505": "War Horn",
    "efa02": "Wind Rider",
    "efk16": "Wings of Light and Shadow",
    "ef412": "A Song for Everybody",
    "efk04": "Adamant Shield",
    "efr07": "Ambrote",
    "efr11": "Andre's Crossbow",
    "efk03": "Aurius",
    "efm15": "Barthez's Orbuculum",
    "ef425": "Blazing Full Moon Trophy",
    "ef426": "Brilliant Confidence",
    "ef401": "Card of Small Miracles",
    "efw10": "Crimson Seed",
    "ef420": "Days of Destiny",
    "efa05": "Dust Devil",
    "efw03": "El's Fist",
    "efa04": "Elyha's Knife",
    "efh08": "Eternus",
    "efw15": "Flower Shower",
    "ef411": "Golden Cocoa Cookie",
    "efw04": "Hell Cutter",
    "efk05": "Hilag Lance",
    "efm08": "Iela Violin",
    "ef428": "III. The Empress",
    "efr03": "Infinity Basket",
    "ef429": "IV. The Emperor",
    "efm04": "Kal'adra",
    "ef402": "Love Potion",
    "efh05": "Magaraha's Tome",
    "ef406": "Midnight Bloom",
    "efa03": "Moonlight Dreamblade",
    "ef415": "Moonlight's Vestige",
    "ef410": "New Year Cookies",
    "ef427": "Nostalgic Music Box",
    "ef423": "Official Levulin Beach Volleyball",
    "ef405": "One Year of Gratitude",
    "ef403": "Portrait of the Saviors",
    "ef432": "Prelude to a New Era",
    "efm09": "Radiant Forever",
    "ef404": "Rainbow Scale",
    "ef424": "Records of Unity",
    "ef409": "Resolute Soldier Series",
    "efr05": "Rosa Hargana",
    "efa06": "Santa Muerte",
    "efr04": "Sashe Ithanes",
    "efw12": "Sepulcrum",
    "efa10": "Shepherds of Chaos",
    "efa11": "Silver Rain",
    "efm05": "Sira-Ren",
    "ef407": "Spooky Solayu Stories",
    "efk10": "Steadfast Gatekeeper",
    "efw05": "Strak Gauntlet",
    "ef413": "Super Duper Water Gun Shooter",
    "efm03": "Tagehel's Ancient Book",
    "efm12": "Tear of the Desert",
    "ef421": "The Guardian Star's Blessing",
    "ef414": "To a New World",
    "ef431": "VII. The Chariot",
    "efh03": "Water's Origin",
    "efh04": "Wondrous Potion Vial",
    "ef417": "XIII. Death",
    "ef422": "XIV. Temperance",
    "ef430": "XIX. The Sun",
    "ef418": "XVI. The Tower",
    "ef419": "XVIII. The Moon",
    "ef307": "Alsacian Spear",
    "ef304": "Ancient Sheath",
    "ef314": "Aqua Rose",
    "ef315": "Ascending Axe",
    "ef306": "Atma's Portal",
    "ef318": "Butterfly Mandolin",
    "ef309": "Cursed Compass",
    "ef317": "Daydream Joker",
    "ef312": "Devil's Brand",
    "ef302": "Egg of Delusion",
    "ef319": "Envoy's Pipe",
    "ef316": "Exorcist's Tonfa",
    "ef321": "Forest Totem",
    "ef313": "Goblin's Lamp",
    "ef301": "Grail of Blood",
    "ef308": "Labyrinth Cube",
    "ef311": "Mighty Yaksha",
    "ef322": "Oath Key",
    "ef303": "Prophetic Candlestick",
    "ef305": "Ranon's Memorandum",
    "ef310": "Sword of the Morning",
    "ef320": "Timeless Anchor",
    "ef205": "Bloodbead Dagger",
    "ef201": "Deadly Sword",
    "ef202": "Elf's Bow",
    "ef204": "Fairy's Grimoire",
    "ef206": "Firm Shield",
    "ef203": "Staff of Wisdom",
    "ef104": "Biting Wind Star",
    "ef102": "Demon's Pistol",
    "ef103": "Dream Scroll",
    "ef106": "Enhanced Gauntlet",
    "ef101": "Sword of the Sun",
    "ef105": "Venus Orb",
}